resources:
  repositories:
    - repository: templates
      type: github
      name: dirigeants/pipelines
      endpoint: dirigeants

jobs:
  - template: lint.yml@templates

  - template: docs.yml@templates
    parameters:
      ghRef: 'github.com/dirigeants/klasa-member-gateway'
      targetBranch: 'docs'
      sync: 'false'
      dependsOn: Lint
